### ISSUE TITLE
Use RVM 

### ISSUE THREAD

**Issue by z-jason** [lsegal/atom-runner#100]
I saw the following errors message when I ran my script

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- awesome_print (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/jiamingz/dev/yozio_web_console/tmp/play.rb:1:in `<main>'
```

I guess that Atom Runner uses my default Ruby to run the script instead of my RVM version. Is there anyway to specify which Ruby bin to use?

**Comment by lsegal** [comment]
See [the README](https://github.com/lsegal/atom-runner/blob/master/README.md), which explains how to customize paths to executables.
