### ISSUE TITLE
run autohotkey scripts

### ISSUE THREAD

**Issue by haichen** [lsegal/atom-runner#109]
At first I'm new with atom. So may be my attempts to use runner are dumb.
I want to run autohotkey scripts.
The program is in 
C:\Program Files\AutoHotkey\AutoHotkey.exe
The extension is .ahk
The PATH is set to C:\Program Files\AutoHotkey

I tried to add this runner config lines to my 
c:/users/user/.atom/config.cson

runner:
  scopes:
    ahk: "C:/Program Files/AutoHotkey/AutoHotkey.exe"
  extensions:
    ahk: "C:/Program Files/AutoHotkey/AutoHotkey.exe"
    
I also tried to add some other versions of this like
"ahk" or 'ahk' or \\ but i didn't get the correct syntax.
So i ask you to help me. And again sorry if this is a totally dumb question.

atom: v1.3.2
atom-runner: v2.5.2
win: windows 10 x32 v1511

**Comment by lsegal** [comment]
@haichen those should be correct. Can you copy relevant output from the runner panel or developer console (Ctrl+Alt+I and navigate to the Console tab) for more info?

**Comment by haichen** [comment]
the console says:
```
atom-runner.coffee:83 No registered executable for file 'C:\Users\haichen\Desktop\test.ahk'
```
My PATH Var
```
ENV PATH:
..Bin;C:\Program Files\AutoHotkey;C:\Program...
```
if you want to try Autohotkey:
https://autohotkey.com/
and here is a small script:

```
;this is a comment
MsgBox "hallo world" 
loop, 10
   FileAppend, index=%a_index%`n, *
;should write this to console
;index=1
;index=2
;...
;index=10
```
Thanks!

**Comment by lsegal** [comment]
The error you're seeing means that atom-runner has no defined executable for the ahk extension. Although your config data above looks correct, it's not actually working properly. Do you have the file correctly indented (with spaces)? The space indentation is significant in cson files, and you need to have it look like:

```
'runner':
  'scopes':
    'ahk': 'C:/Program Files/AutoHotkey/AutoHotkey.exe'
```

**Comment by haichen** [comment]
OK.. I thought I had done it correctly with the space idention
Now the console tab don't show an error!
but
Atom Runner:test.ahk shows the complete PATH Var and the following Errors:
```
ENV PATH: C:\Progr...l\atom\bin;C:\Program Files\AutoHotkey;C:\Program...

Error: spawn C:/Program ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

My complete config.cson looks completely as this now:
```
"*":
  "exception-reporting":
    userId: "...."
  welcome:
    showOnStartup: false
  editor:
    invisibles: {}
  core:
    themes: [
      "atom-light-ui"
      "atom-light-syntax"
    ]
  'runner':
    'scopes':
      'ahk': 'C:/Program Files/AutoHotkey/AutoHotkey.exe'
```

**Comment by haichen** [comment]
``` 
 'runner':
    'extensions':
      'ahk': 'C:/Program Files/AutoHotkey/AutoHotkey.exe'
```
It doesn't take the whitespace in `C:/Program Files/`. Can I escape it?

**Comment by lsegal** [comment]
@haichen since you have AutoHotkey in your PATH, you really only need to use the executable name:

```
'ahk': 'autohotkey.exe'
```

**Comment by haichen** [comment]
Thank you very much. That solves the problem. It was not really clear for me, because the powershell example uses the complete path.
