### ISSUE TITLE
Scrolled too far down

### ISSUE THREAD

**Issue by pTran24** [lsegal/atom-runner#113]
Hi, when I am running a script, the output shows up but I have to scroll up to see it. Restarting ATOM doesn't help and the scroll bar just gets smaller and smaller as I run scripts.

atom-runner 2.5.2 Windows 10

**Comment by lsegal** [comment]
I can't reproduce this on Windows 10. Do you have a minimal case that reproduces the issue?

**Comment by pTran24** [comment]
Hi,

Thanks for your quick response, I believe this is with Atom itself, I may have installed some package causing this bug or something. I noticed this when I was looking at my packages and once I scrolled down beyond a point, they were invisible to me even though I was still able to scroll down and click on them.

This is not an issue with your package. Even though this isn’t your issue, would you happen to have experienced this yourself?

Thanks,
