### ISSUE TITLE
Re-open atom-runner window on start-up

### ISSUE THREAD

**Issue by kbrose** [lsegal/atom-runner#114]
It would be nice to re-open the atom-runner window the next time Atom is opened (only when it was open when Atom was closed, of course).

Is it even possible for an atom package to do that?

**Comment by lsegal** [comment]
I think it might be possible, but I'm not sure. If you opened a PR that added this behavior I would likely accept it.

**Comment by lsegal** [comment]
Closing. If you are interested in this, please submit a PR.
