### ISSUE TITLE
python / python3 are on PATH but runner can't find it ?

### ISSUE THREAD

**Issue by chromafunk** [lsegal/atom-runner#116]
I am on a Debian stretch, executing atom as regular user. The user has ENV PATH: /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/sbin:/sbin, but runner insists the bin is not in path .... how can I look further to debug this issue ?

**Comment by lsegal** [comment]
Loading up the atom developer console should show some debug information from the plugin as to what it sees your ENV as.

**Comment by chromafunk** [comment]
how do you open it ? I just started configuring it !

**Comment by lsegal** [comment]
[This](https://discuss.atom.io/t/how-to-view-console-window-debugger/10098) should help you.

**Comment by lsegal** [comment]
Closing this because, in my experience, a missing file error from the system is almost always an environment issue, not one with the plugin. You should verify with `which python` that it is in one of the listed paths. Note that atom-runner executes python by default, not python3.
