### ISSUE TITLE
My PATH isn't configured correctly?

### ISSUE THREAD

**Issue by VenusY** [lsegal/atom-runner#117]
Whenever I try to run my code using alt+r, it comes up with this huge block of text and the code doesn't run. Basically, it doesn't work and I don't know how to fix it. Does anyone have the solution to this? This is probably a really stupid question, but, in all fairness, I am new to the world of coding and I literally just got packages to work a few minutes ago.
![screenshot_1](https://cloud.githubusercontent.com/assets/17103798/12876906/6c1fd1a0-ce01-11e5-91e8-99b4cd69131a.png)

**Comment by lsegal** [comment]
Loading up the atom developer console should show some debug information from the plugin as to what it sees your ENV as. The developer console tab should be available from View -> Developer -> Toggle Developer Tools (click the "console" tab in the pane that opens).

**Comment by VenusY** [comment]
I've opened the console tab, what do I do now?

**Comment by VenusY** [comment]
My operating system is Windows by the way, I don't know if this information is important or not, but it's there if it is.

When I open the console there are 2 logs and they both have a yellow triangle with an exclamation mark in it next to them.

**Comment by lsegal** [comment]
While the console tab is open, atom-runner will provide log information about the PATH information. Run your script with the window open and paste the reported lines.

**Comment by VenusY** [comment]
I think I've fixed that issue, but what do I do about "Unable to find command: python"?

**Comment by lsegal** [comment]
> While the console tab is open, atom-runner will provide log information about the PATH information. Run your script with the window open and paste the reported lines.

Please do this to provide information about your issue.

**Comment by VenusY** [comment]
Do I paste the ENV PATH into the console?

**Comment by VenusY** [comment]
This is what it says when I do that.

Uncaught SyntaxError: Unexpected token ILLEGAL
    at Object.InjectedScript._evaluateOn (<anonymous>:904:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:837:34)
    at Object.InjectedScript.evaluate (<anonymous>:693:21)

**Comment by lsegal** [comment]
@VenusY please paste the resulting PATH information from the debug log into this issue so we can look at why python is not found. If you want, you can debug this yourself: `python.exe` must be inside one of the semi-colon delimited paths provided by the PATH variable. If there is no `python.exe` in any of these paths, then you will need to add the Python directory to your PATH. 

You can find information on how to do this in the [Python documentation](https://docs.python.org/3/using/windows.html).

**Comment by VenusY** [comment]
Thank you. Sorry if I'm asking really stupid questions, I'm quite new to this as you can tell.

**Comment by VenusY** [comment]
C:\Users\Venus Yip\AppData\Local\atom\app-1.5.2\resources\app.asar\src\deserializer-manager.js:47 No deserializer found for Object
index.js:52 Window load time: 1946ms
C:\Users\Venus Yip\AppData\Local\atom\app-1.5.2\resources\app.asar\src\text-editor-component.js:957 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
C:\Users\Venus Yip\AppData\Local\atom\app-1.5.2\resources\app.asar\src\text-editor-component.js:957 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

**Comment by VenusY** [comment]
Is this what you wanted me to do?

**Comment by lsegal** [comment]
No. I actually forgot that your ENV PATH now shows up in the error message itself. When you see the "Unable to find command: python", can you copy *the entire error*, not just the first two lines?

**Comment by VenusY** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/17103798/12995756/bd109d1a-d121-11e5-8c7a-03545cc5e3d3.png)

**Comment by lsegal** [comment]
So as mentioned above, you must configure your PATH to include the Python executable directory. Unfortunately it's out of the scope of this project to provide that kind of support, but you can read the Python docs linked above, which should explain how to do this.

I am marking this issue as closed because this is expected behavior for atom-runner and a configuration issue.

**Comment by VenusY** [comment]
Okay, thanks for your help.
