### ISSUE TITLE
unable to find node in OSX

### ISSUE THREAD

**Issue by tofutim** [lsegal/atom-runner#121]
I launch atom from the command line (where node works), but it doesn't pick it up. It is in /usr/local/bin/node.

Unable to find command: node
Are you sure PATH is configured correctly?

ENV PATH: /usr/bin:/bin:/usr/sbin:/sbin

Error: spawn node ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by tofutim** [comment]
I'm running atom from the command line. From that same command line

Tims-MacBook-Air:~ tim$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/MacGPG2/bin
Tims-MacBook-Air:~ tim$ atom

and yet /usr/local/bin is not in the error message.

Atom Runner: app.js

Unable to find command: node
Are you sure PATH is configured correctly?

ENV PATH: /usr/bin:/bin:/usr/sbin:/sbin

Error: spawn node ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
Running: node /Users/tim/Projects/qi.Email/src/app.js (pid undefined)

**Comment by tofutim** [comment]
I think this is a Yosemite issue - see https://github.com/atom-community/linter/issues/150

"I upgraded to Yosemite and now Atom doesn't seem to inherit the $PATH from the shell I launch atom from. So this issue is now pretty important to fix.

I started working on it a while ago but never finished it. But since my linter is now broken, I'll fix this issue on the weekend."

**Comment by tofutim** [comment]
Somehow it started working now. I had to Ctrl-R two times, the first time fails but the second time works.

**Comment by BastienL** [comment]
@tofutim, have a look at [https://github.com/steelbrain/linter/issues/150#issuecomment-99426665](https://github.com/steelbrain/linter/issues/150#issuecomment-99426665)

I had the same problem as you (had to Ctrl-R two times to make it work) but with this fix it works the first time.
