### ISSUE TITLE
Runner does not work while in Vim Normal Mode

### ISSUE THREAD

**Issue by itsbriany** [lsegal/atom-runner#123]
I ran into an issue when running a python script while using the [Vim Mode](https://github.com/atom/vim-mode) plugin. 

When I am in vim normal mode, I cannot run the script, but I can still run it while in vim insert mode.

OS: Mac OSX 10.11.3

**Comment by lsegal** [comment]
Can you explain what does not work, exactly? Reproduction steps would be helpful, along with any error logs or expectations and a description of what happened.

**Comment by itsbriany** [comment]
Expected behavior:
Atom-runner runs the python script

Reproduction steps that do not cause expected behaviour:
1. Open a python script in Atom (with the Vim Mode and Atom-runner packages enabled)
3. Click on the editor pane showcasing the python script
2. Ctrl + R in an attempt to run Atom-runner


Reproduction steps that produce expected behaviour:
1. Open a python script in Atom (with the Vim Mode and Atom-runner packages enabled)
2. Click on the editor pane showcasing the python script
3. Press **i** (triggers Vim Insert Mode)
4. Ctrl + R in an attempt to run Atom-runner

**Comment by lsegal** [comment]
Looking at Vim Mode, it looks like they also use Ctrl+R as a keybinding, so there is a collision here.

You can re-bind the keybinding for running atom-runner (or Vim Mode) in Atom's settings under the Keybindings tab.

Unfortunately there is no other solution to this other than rebinding your keys. There's no code change we could apply that would fix this.
