### ISSUE TITLE
Uanble to run programm under windows 10 and python 3.5

### ISSUE THREAD

**Issue by claudioarchi** [lsegal/atom-runner#125]
First of all thank you for the package it seams really cool to run code from atom. But I can't get it to work:
this is the message that I get : 
Unable to find command: python
Are you sure PATH is configured correctly?

My python is installed on my c drive so I gave this path top atom-runner in to my config.cson
atom-runner:
       python : "C:\\Python35\\python.exe"

but still don't work.

Any idea
Thank you

BTW: I'm very new to atom and coding, so maybe the problem is on my side

**Comment by lsegal** [comment]
See the readme for correct syntax in configuring the config.cson file. Note also that spaces are significant in the cson file format.

**Comment by claudioarchi** [comment]
Thank you for your reply. Do you mean coping the provided code in the readme on my config.cson. 
At the moment the 'atom-runner' is at the very beginning of that file does make any difference where that code it's located. 
And what about ENV PATH. Where can I change it

**Comment by lsegal** [comment]
I mean that the syntax and formatting (including spaces) matters in the configuration file. Note that it starts with runner, not atom-runner. Please use the README's example as a base for your configuration changes.

As for setting your path, this is out of the scope of the plugin, but you can [read how to configure PATH under Windows here](http://www.computerhope.com/issues/ch000549.htm).

**Comment by claudioarchi** [comment]
Thank you again, It was actually the Env Path the problem, I corrected using the link you provided.
Now Run some programs without any troubles, but when a code requires an input from the user the plug-in returns an error. Is this something known.
thank you

**Comment by lsegal** [comment]
Reading from STDIN is not supported. See #98

**Comment by devf33** [comment]
Hey the my config.ison file has the last line of code written showOnStartup: false, do i continue in the 14th line with 'runner' : ?
