### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by jayparekhjp** [lsegal/atom-runner#126]
tried installing many times but every time i hit alt+r, nothing happens.

**Comment by Ispeakmusic** [comment]
same problem here..

**Comment by lsegal** [comment]
Please provide steps to reproduce the issue (did you open a file? Create a new one? What language was it set to? etc) including details about your system environment (Operating System, plugin version, etc). I can't provide much help with this issue as is.

**Comment by lsegal** [comment]
Closed with no reproduction steps.
