### ISSUE TITLE
Error: spawn python ENOENT

### ISSUE THREAD

**Issue by whathaveidone11** [lsegal/atom-runner#127]
I've search the internet and I understand this problem is to do with the 'PATH' but I do not understand any proposed solutions or what is mentioned in the Auto-Runner FAQ.

I have Windows and Python 3.5 installed, followed by Atom. I used this guide to set myself up to learn Python - https://www.youtube.com/watch?v=uve1tjVIQ6c

-----------------------

However running any code with ALT+ R returns the following-

Unable to find command: python
Are you sure PATH is configured correctly?

ENV PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;E:\quicktime\QTSystem\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\Edward\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\Edward\AppData\Local\Programs\Python\Python35\;C:\Users\Edward\AppData\Local\atom\bin

Error: spawn python ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

---------------------------

For what its worth my environment variable for PATH is - 

C:\Users\Edward\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\Edward\AppData\Local\Programs\Python\Python35\;C:\Users\Edward\AppData\Local\atom\bin

**Comment by lsegal** [comment]
Your PATH needs to include at least one directory with the `python.exe` binary inside of it. My guess is that none of the directories you listed at the end have the executable in them. You should go into your Python35 directory and look for the `python.exe` binary (usually in a bin\ sub-directory) and use *that* path in your environment variable.

**Comment by whathaveidone11** [comment]
Thanks for the reply, I found python application exe at the following directory C:\Users\Edward\AppData\Local\Programs\Python\Python35 should I add this onto the path environment variable?

**Comment by lsegal** [comment]
Yes.

**Comment by lsegal** [comment]
Closing since this is an environment/configuration issue and atom-runner is working correctly.

**Comment by adzie95** [comment]
where is the python.exe binary and where is the environment variable
