### ISSUE TITLE
Changing theme of runner window

### ISSUE THREAD

**Issue by zelator29** [lsegal/atom-runner#133]
Is there an easy way to change the runner window colors from dark grey on slightly-less-dark grey?

**Comment by lsegal** [comment]
atom-runner should be using your window theme settings. see #84. If you want to make some tweaks that work a little more consistently across different theme settings, I'd welcome a pull request!

**Comment by lsegal** [comment]
Closing. If you are interested in tweaking this, please submit a PR.
