### ISSUE TITLE
Python: input()

### ISSUE THREAD

**Issue by TechNiklas** [lsegal/atom-runner#135]
I'm using your atom-runner

By using the input() function I get the issue:
**`EOFError: EOF when reading a line`**

> Please write your name: Traceback (most recent call last):
>   File "C:\Users\Niklas\Desktop\atom.py", line 10, in <module>
>     word = input("Please write your name: ")
> EOFError: EOF when reading a line

Any idea for troubleshooting that issue? 

Regards
TechNiklas

**Comment by mstgnz** [comment]
same problems :/
