### ISSUE TITLE
Runner window position

### ISSUE THREAD

**Issue by esledov** [lsegal/atom-runner#136]
Is it possible to make runner window to dock at the bottom rather then at the side?

Thank you.

**Comment by lsegal** [comment]
It is possible to do this with a change to atom-runner. I would accept a patch that implemented this as an option toggle.

For what it's worth, the line in question [is here](https://github.com/lsegal/atom-runner/blob/master/lib/atom-runner.coffee#L91). You would just need to change that to `splitDown`. You could go into your packages directory and make this change locally if you were interested.

**Comment by lsegal** [comment]
Actually I just added this in 2.6.0, it was an easy change. You should be able to toggle this in the plugin settings now.
