### ISSUE TITLE
Windows 10 Powershell won't run

### ISSUE THREAD

**Issue by zlegault** [lsegal/atom-runner#140]
Running into an issue getting this to execute Powershell on Windows 10 as it's looking for the Sysnative file path. Am I missing something painfully obvious here?

**Comment by lsegal** [comment]
I cannot reproduce this because the issue lacks any reproduction steps. You might be missing something, but I have no way of knowing what that thing is, since there is almost no information about your actual issue. 😊

**Comment by lsegal** [comment]
Closing due to lack of reproduceability. Please see the FAQ section in the README on the GitHub project page for how to properly report an issue. Thanks.
