### ISSUE TITLE
Atom-runner

### ISSUE THREAD

**Issue by derekonguyen** [lsegal/atom-runner#143]
I am doing a tutorial and receive an error code when trying to run the below code. I placed the error code below the code I was trying to run. 

I am running Windows 7, Service pack 1
I am using Python 3.5.1

my_name = 'Zed A. Shaw'
my_age = 35 # not a lie
my_height = 74 # inches
my_weight = 180 # lbs
my_eyes = 'blue'
my_teeth = 'white'
my_hair = 'brown'

print "Let's talk about %s." % my_name
print "He's %d inches tall." % my_height
print "He's %d pounds heavy." % my_weight
print "Actually that's not too heavy."
print "He's got %s eyes and %s hair."
print "His teeth are usually %s depending on the coffee." % my_teeth

# this line is tricky, try to get it exactly right
print "If I add %d, %d, and %d I get %d." % (
my_age, my_height, my_weight, my_age + my_height + my_weight)

I am hoping to be able to try running the code in python 3.5.1 as well. Below is the error I received in Atom when trying to run the above code:

Unable to find command: python
Are you sure PATH is configured correctly?

ENV PATH: undefined

Error: spawn python ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)

**Comment by lsegal** [comment]
You don't have a PATH configured. See [the FAQ](https://github.com/lsegal/atom-runner#faq-and-known-issues) for how to fix this.
