### ISSUE TITLE
Add command line arguments with runner

### ISSUE THREAD

**Issue by migabriel** [lsegal/atom-runner#144]
Hi,

I'm running on python3 Ubuntu 14.04. With the argparser module I execute my script by:

./script.py --input /path/to/input

How do I tell runner to use "--input /path/to/input"?

Cheers

**Comment by lsegal** [comment]
Runner doesn't really support adding command line arguments, it's meant as an interactive way to run small scripts while you edit them for "testing".

One thing you can usually do in these situations is to fake the command line arguments in your scripting environment. Something like:

```
sys.argv = ['new', 'arguments', 'here']
```

**Comment by lsegal** [comment]
Closing since a workaround is supplied.
