### ISSUE TITLE
Set bash variable before execution of script

### ISSUE THREAD

**Issue by h-a-n-n-e-s** [lsegal/atom-runner#145]
Hi,

When I run a gnuplot script, I need to set a bash variable which I use inside the script.
In the command line, I normally write
`variable=value gnuplot script.gp`
If I put that into config.cson, the run:file command doesn't work.
Is there any way to do this in atom-runner?

Thanks

**Comment by lsegal** [comment]
atom-runner doesn't spawn in a shell by default, which means it doesn't process your line as a shell string (and therefore does not parse environment variable syntax). It does look like gnuplot accepts variables using the `-e` flag though:

```
$ gnuplot -e "filename='foo.data'" foo.plg
```

So you could use that syntax in config.cson.

See: http://stackoverflow.com/questions/12328603/how-to-pass-command-line-argument-to-gnuplot

I would also accept a PR to toggle spawning under a shell as an option.

**Comment by h-a-n-n-e-s** [comment]
The 'gnuplot -e' version would be great, if gnuplot would accept escape characters for quotes from config.cson:
`gnuplot: "gnuplot -e 'name=\"value\"' script.gp"`
but it doesn't!
So there is the problem that the entry in the config.cson is already in double quotes, and then I need another single quotes and then ANOTHER double quotes.
I found no way to do it.
Any ideas?

**Comment by lsegal** [comment]
The single quotes are meant to be interpreted by your shell. Since there is no shell layer, you do not need the single quotes. Note that this means you cannot have values with spaces, but it should work without the single quotes.

**Comment by h-a-n-n-e-s** [comment]
You're right, this works:
`gnuplot: "gnuplot -e name=\"value\""`
Thanks a lot!
