### ISSUE TITLE
mistakes when import usrlib.request

### ISSUE THREAD

**Issue by forrestchang** [lsegal/atom-runner#148]
When I import `urllib.reques` in the script and use `Ctrl-r` to run it,  it shows like:

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from urllib.request import urlopen
ImportError: No module named request
```

I test it in the Python interpreter, it works and has no mistakes.

This is my config code in `config.cson` file:

```
    runner:
      python: "/usr/local/bin/python3"
```

**Comment by lsegal** [comment]
This is not a problem with atom-runner. It looks like your python application is misconfigured. Atom-runner doesn't have any Python in its codebase and cannot generate Python stacktraces on its own.
