### ISSUE TITLE
Is possible to run php files? php installed in portable xampp directory

### ISSUE THREAD

**Issue by oxk4r01** [lsegal/atom-runner#152]
I attempted it in this fashion, but with no results. Quotation marks and format from the lines added to config.cson disappeared after restart Atom

"runner":
  "scopes":
    '"php": "C:\\xampp\\php\\php.exe"

Thanks in advance

**Comment by lsegal** [comment]
It is possible to run php files. Please follow the correct bug report format if you wish to open a new issue. Thanks.
