### ISSUE TITLE
ES2015 "..." not supported?

### ISSUE THREAD

**Issue by netsi1964** [lsegal/atom-runner#153]
Hi,

I love your package, it's great! :-)
I was playing around with some ES2015 feature and especially the "..." feature. My code fails to run in atom-runner. The code runs when using Babel test site.

```
var a = {
  street: "test",
  number: 3
}

console.log(a);

function update(obj) {
  return {
    ...obj,
   number: 32
  }
}

console.log(update(a))
```

I get this error:

```
    ...obj,
    ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
```

Is it because there is not 100% support for all ES2016 features?

**Comment by lsegal** [comment]
Looks like you're just using a version of Node.js that does not support your features. `console.log(process.version)` will tell you what you are running.

Atom-runner doesn't parse or execute your code directly, so this is not an issue with the plugin.
