### ISSUE TITLE
No output for php files

### ISSUE THREAD

**Issue by oxk4r01** [lsegal/atom-runner#154]
Despite it's working with js I don't get any kind of output for php. I added some lines to config.json but I got an error: 'unexpected new line' 
"runner":
    "scopes":
      "php": "php"

What could be the problem?

**Comment by lsegal** [comment]
I can't reproduce this. Please follow the bug report guidelines when opening an issue so that it can be triaged properly.

**Comment by yoesoff** [comment]
I'm having same issue here with atom runner and atom 1.22.1
