### ISSUE TITLE
How to tell runner to differentiate between nodejs files and mocha tests?

### ISSUE THREAD

**Issue by erelsgl** [lsegal/atom-runner#155]
When I click Alt+R in a Mocha test, whose filename ends with "js", I get an error ""ReferenceError: describe is not defined".   This is probably because atom-runner tries to run the file with "nodejs" instead of "mocha". In the configuration file, I have the following lines:

      'js': 'nodejs'
      'mocha': 'mocha'

Apparently, this does not work , atom-runner treats the Mocha file as a Node.js file. How can I make it run  Mocha tests using mocha?

**Comment by lsegal** [comment]
You can use the `extensions` map to configure different languages for different extension suffixes, this is explained in the [README](https://github.com/lsegal/atom-runner#configuring) with an explicit example for mocha.
