### ISSUE TITLE
How to setup Python environment?

### ISSUE THREAD

**Issue by peporiz0r** [lsegal/atom-runner#156]
Mac OS 10.11.6, Atom 1.9.9, atom-runner 2.7.0

Hello,

I'm working on this now for hours and it's driving me crazy.
What is the right way to define the correct python environment I want to work with?
I want to run my code in atom via a specific anaconda environment, but it either keeps using python2 or throws all kinds of errors at me. I tried different syntaxes in the config.cson, but all without success. 
What do I have to do?

My latest try was:

```
"*":
  editor:
    tabLength: 4
  "exception-reporting":
    userId: "..."
  runner:
    scopes:
      python: "/Users/Air/anaconda/envs/Python3/bin"
```

but i get an error: spawn EACCES
please help me

**Comment by lsegal** [comment]
I can't reproduce this. Please follow the instructions in the README (https://github.com/lsegal/atom-runner), which provides enough information to debug your environment details, specifically potential PATH issues.
