### ISSUE TITLE
Python working directory is set by project folder, not the path of the file

### ISSUE THREAD

**Issue by peporiz0r** [lsegal/atom-runner#162]
Following scenario:
You open a (.py) File in /dir_A/ and work on it./dir_A/ is now your project folder in atom. If you run it with atom-runner, your cwd is /dir_A/.
Now you open a second file in atom (by clicking on it in your file explorer), located in /dir_B/.Your project folder didn't change. But if you run that second file in atom-runner, your cwd is still /dir_A/ and NOT the dir of that file.
This can cause major problems for instance if you try to import modules or working on other files. Took me a lot time bug fixing, as all of a sudden my files and modules couldn't be found.

Would be better if atom-runner changed to the dir of the specific file, wouldn't it?

**Comment by lsegal** [comment]
atom-runner uses the cwd provided by Atom, which is consistent with the way Atom works (a project directory is expected to be your working directory). You should open a separate project directory or don't rely on relative paths if you work with filesystem data. In general, you should not rely on paths relative to your working directory if your programs expect data in specific locations on disk.
