### ISSUE TITLE
path not correctly configured

### ISSUE THREAD

**Issue by derekonilsen** [lsegal/atom-runner#166]
So I am just getting started with javascript and have written a income tax calculator. However, when I try to run the program in atom runner I get the following error:

Unable to find command: node
Are you sure PATH is configured correctly?

ENV PATH: C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Users\DerekON\AppData\Local\Microsoft\WindowsApps

Error: spawn node ENOENT
    at exports._errnoException (util.js:1008:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

I had this problem before with python however I was easily able to fix it by reinstalling python and checking a box that read something like configure path during the install however atom doesn't give me that option. 

I appreciate the help if someone knows what I could do to correctly configure the path.

Thank you,

Derek

**Comment by derekonilsen** [comment]
I tried to bring up this issue in my intro to programming class however nobody is able to help me resolve the issue(configuring the path).

**Comment by derekonilsen** [comment]
now i'm not getting the path error. however, now I am getting a syntax error that reads as follows

C:\Users\DerekON\Desktop\School\income_tax_calculator.js:2
import java.util.scanner;
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

I'd be happy to provide the code as well if someone thinks that is necessary to solve the issue.

someone thinks that is necessary.

**Comment by lsegal** [comment]
Your .js file includes Java code. [JavaScript and Java are not the same language](https://www.java.com/en/download/faq/java_javascript.xml).

**Comment by derekonilsen** [comment]
so the java.util.scanner is java not javascript? ok, that much makes sense to me however
I am unable to find the correlating code in javascript.

**Comment by lsegal** [comment]
Unfortunately that question is out of scope for the atom-runner project. You might want to look up some JavaScript tutorials to properly understand the capabilities of the language. Or possibly consider using Java.

**Comment by derekonilsen** [comment]
ok, thanks for the advice
