### ISSUE TITLE
wrong current working directory

### ISSUE THREAD

**Issue by watashiSHUN** [lsegal/atom-runner#168]
I have version 2.7.1 so I believe it is a different issue than #28 
this happens when I have multiple project folders opened in atom:

`os.getcwd()` will return the **the top project folder in the navigation bar** even if I am working under a different project folder...if I try to create a file using relative path (with atom runner), it will result in the wrong place

![capture](https://cloud.githubusercontent.com/assets/6531400/21164553/a64a152a-c14e-11e6-9b92-5e562a6bf83d.JPG)

**Comment by lsegal** [comment]
Atom-runner uses Atom's project path-- if Atom is returning folder1 as your project path, there's not much runner can do about that.
