### ISSUE TITLE
the runner doesn't allow user input in Python 3

### ISSUE THREAD

**Issue by Kamillife** [lsegal/atom-runner#170]
This is the traceback below:

y2 = Traceback (most recent call last):
  File "/*******/PyWork/slop.py", line 7, in <module>
    y2 = float(input("y2 = "))
EOFError: EOF when reading a line

And this is my code:

y2 = float(input("y2 = "))

**Comment by lsegal** [comment]
Reading from STDIN is not supported. Patches accepted to add this.
