### ISSUE TITLE
Is it possible to redirect atom-runner output to a file ?

### ISSUE THREAD

**Issue by jackgriffin63** [lsegal/atom-runner#172]
Please read this notice and then remove this content to show that you have understood
the contents:

**If you are submitting a bug report, please ensure you are following the steps below:**

1. Before you open this bug report, please make sure that you have properly configured the
plugin for your environment. There are a lot of external factors that can cause the plugin to fail
that are dependent on the language you are using, the code you are writing, the OS you are on,
and much more. Please be mindful that this plugin is developed for many different languages
and third-party tools, and the details of a single environment may not be immediately obvious.

2. If you are still having the issue, please make sure that you provide detailed steps and include
your environment (OS), language, and, if relevant, any source code you executed when running
into the issue. Without this information, it is not always possible to know what is broken, and this
will slow down the ability to provide a quick patch for any bugs.

3. Opening a bug report that only says the plugin is "not working" is not helpful and will likely
end up being closed due to lack of reproduceability. Unfortunately it is not possible to provide
detailed configuration instructions for each language and/or environment combination in the
bug tracker. Your issue **MUST** include reproduction steps.

**If you are submitting a feature request:**

1. Note that feature requests may not be implemented by project maintainers. If you wish to have
your request implemented, it is better to submit a pull request with working code. If you are not
sure if this project will accept this feature and it is a large implementation, feel free to open an
issue asking if such a feature would be accepted first.

2. Features that will not be implemented by the maintainers may be closed immediately. This
is for issue management purposes and does not necessarily mean the idea is bad. It simply
means that there are no plans for this to be implemented by the maintainers. In this case,
the message should indicate whether a pull request would be looked at or not.

**Comment by lsegal** [comment]
Closing as invalid. This is not an issue.
