### ISSUE TITLE
Update URL in atom-make-runner.less

### ISSUE THREAD

**Issue by pinophyta** [lsegal/atom-runner#176]
URL included in https://github.com/fiveisprime/atom-make-runner/blob/master/styles/atom-make-runner.less is not working:

Doesn't work: 
`// See https://github.com/atom/atom-dark-ui/blob/master/stylesheets/ui-variables.less`

Works:
`// See https://github.com/atom/atom-dark-ui/blob/master/styles/ui-variables.less`

**Comment by lsegal** [comment]
I would accept this as a pull request.
