### ISSUE TITLE
How can you increase the text size of the Atom Runner outputs?

### ISSUE THREAD

**Issue by miltondavila** [lsegal/atom-runner#177]
Hi,

I would like to know how can I increase the text size of the Atom Runner's output?

![image](https://cloud.githubusercontent.com/assets/3312235/23085832/e8bc677e-f537-11e6-9dee-0376d64cbd91.png)

Thanks for your help.

**Comment by namioto** [comment]
.atom-runner pre { font-size: 1.5em; }

**Comment by miltondavila** [comment]
Thanks for your help.
