### ISSUE TITLE
Ubuntu alt key in use.

### ISSUE THREAD

**Issue by mangueLinux** [lsegal/atom-runner#178]
In Ubuntu alt key is in use. Change it to F5.

**Comment by lsegal** [comment]
Sorry, this keybinding has been around for a while (multiple years now). Changing it would break users. You can change this in your local configuration.

**Comment by tanmayameher** [comment]
Hello, i sort of reopened it; but i just want to change it to my own convenient key (let's say F5). Where should i change the keymap setting? the atom-runner.cson  file in the keymaps folder?! i tried that and put something like below.

`'F5': 'run:file'
  ''F6': 'run:selection'`

But didn't work. Please help :)
