### ISSUE TITLE
Cannot read/write to external files using python

### ISSUE THREAD

**Issue by G31M3R** [lsegal/atom-runner#199]
Running Python3 (properly configured) on MacOS, when running a program that reads and writes to a config.txt (open("config.txt", 'r')), it says: "IOError: [Errno 2] No such file or directory: 'config.txt'
" even though I know for a fact that the file exists in the same folder

**Comment by lsegal** [comment]
`open` reads from your current working directory. That's not necessarily the same directory as the file you're running. By default, Atom-runner uses your workspace / project directory as the working directory.
