### ISSUE TITLE
Zombie runners 🧟‍♂️🧟‍♀️

### ISSUE THREAD

**Issue by adavidzh** [lsegal/atom-runner#215]
I just came out of a session of re-re-re-re-running the same script that would for one reason or another not exit.
Is it a feature that all processes spawned by `atom-runner` live until they quit or someone kills them?
If so, is there a way to get a list of processes from inside atom and then kill them?
If not, is there a way to get a key binding to kill all spawned processes?
Or since the same pane is re-used for every usage `Ctrl-R` should the previous process, if any, be killed first?

**Comment by lsegal** [comment]
Processes should be killed when Ctrl-R is called. If not, there is a bug, or the process itself is not dying properly (we send a SIGINT to the process that it must be able to handle).

**Comment by adavidzh** [comment]
I think this may all be my fault since I was playing with python's `multiprocessing.Process`. Closing and thanks for replying.
