### ISSUE TITLE
There is a leading ^C in the output

### ISSUE THREAD

**Issue by rogergl** [lsegal/atom-runner#33]
If I use node.js to run 

console.log("Hello World");
console.log("Hello World");

I get

^CHello World
Hello World

**Comment by lsegal** [comment]
Do you by any chance have your run key bound to the same key as the kill command (Ctrl+Shift+C by default)? Or is that key bound to anything else you might be hitting? That's the only reason the "^C" flag would show up in output.

**Comment by rogergl** [comment]
No, the key was bound to Ctrl-R. Nevertheless I updated node.js and Atom and the ^C disapeared.

**Comment by lsegal** [comment]
Glad you got it working. Sounds like this can be closed then!
