### ISSUE TITLE
[feature] copy-paste

### ISSUE THREAD

**Issue by picibucor** [lsegal/atom-runner#35]
Hi all,
I would like to have copy-paste  feature. I am able to mark the output/error, but the common CTR-C keys do not copy the text.  Copying the outputted error-code(s) would make the life easier. 

![screenshot](https://cloud.githubusercontent.com/assets/1676457/5916217/05b0bd00-a60f-11e4-9754-4d421070c775.png)

Win7
Python 3.4
atom 0.175.0

**Comment by LeopoldoFu** [comment]
:+1: This would be very helpful in general.  I'd be more inclined to say this is a bug.

**Comment by hemme** [comment]
:+1:

**Comment by lsegal** [comment]
Patches accepted! +1's won't help. Thanks!

**Comment by lsegal** [comment]
Copy paste should work now, please open a pull request if you still have this problem.
