### ISSUE TITLE
EOFError: Error when reading a line

### ISSUE THREAD

**Issue by vitorcarvalhoml** [lsegal/atom-runner#42]
Hi, I'm having a bit of a problem while running python scripts on osx and windows 8.1.
![unnamed](https://cloud.githubusercontent.com/assets/997100/6376609/c6541106-bcfd-11e4-97c0-e7d800130967.png)

Could someone help me please?

**Comment by lsegal** [comment]
atom-runner does not support reading input from stdin, currently.

**Comment by vitorcarvalhoml** [comment]
Thanks @lsegal! I will read from a file.

**Comment by droidzone** [comment]
Any workaround for this?
