### ISSUE TITLE
Runner: Stop does not kill golang process

### ISSUE THREAD

**Issue by euforic** [lsegal/atom-runner#5]
Example running the code below with __cmd-R__
Then executing __ctrl-c__ does not kill the running process
Using the keyboard shortcut or the command menu option.

Example Code
```go
package main

import (
	"fmt"
	"net/http"
)

type String string

type Struct struct {
	Greeting string
	Punct    string
	Who      String
}

func (s String) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	fmt.Fprint(w, s)
}

func (s *Struct) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "%s %s %s", s.Greeting, s.Punct, s.Who)
}

func main() {
	// your http.Handle calls here
	http.Handle("/string", String("I'm a frayed knot."))
	http.Handle("/struct", &Struct{"Hello", ":", "Gophers!"})
	http.ListenAndServe("localhost:4000", nil)
}
```

**Comment by damonkreft** [comment]
Yeah, same issue running the HTTP server in Go on Ubuntu. Go web/network development using this plugin would be tremendous, but not really feasible at the moment.

**Comment by ioquatix** [comment]
@damonkreft We've recently had a PR for handling multiple panes and killing things correctly, https://github.com/ioquatix/script-runner/pull/9 - we haven't released a new version yet on NPM but if you'd be able to test out the latest master branch and report back on that PR that would be great.

**Comment by lsegal** [comment]
Closing this old issue because it's unclear that this is still an issue. If it is, please provide a patch that resolves this, thanks!
