### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by nuckle96** [lsegal/atom-runner#50]
Requiring `ScrollView` from `atom` is no longer supported.
Please require `ScrollView` from `atom-space-pen-view` instead:
  `{ScrollView} = require 'atom-space-pen-views'`
Note that the API has changed slightly! Please read the docs at https://github.com/atom/atom-space-pen-views
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
```
Object.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/exports/atom.js:80:11)
Object.<anonymous> (/Users/nuckle96/.atom/packages/atom-runner/lib/atom-runner-view.coffee:1:1)
```

**Comment by lsegal** [comment]
Closing. Open a pull request to fix this, thanks!
