### ISSUE TITLE
Can't display Chinese

### ISSUE THREAD

**Issue by dragonholiday** [lsegal/atom-runner#53]
Can not display Chinese. I seems that the default font doesn't support Chinese.
![screenshot from 2015-05-08 15 43 43](https://cloud.githubusercontent.com/assets/3395087/7532417/2860c640-f599-11e4-8f0c-0432ecc0d4bd.png)

I've tried to edit the atom-runner.less file,
![screenshot from 2015-05-08 15 47 03](https://cloud.githubusercontent.com/assets/3395087/7532454/9abec26e-f599-11e4-9e16-667500f854a1.png)

 but it didn't work. Please give a guide to solve this problem, and   hope to fix it.

**Comment by lsegal** [comment]
Unfortunately I have no guide to solve this, but if you figure it out feel free to open a pull request.

**Comment by dbolton** [comment]
@dragonholiday I came across the same problem. It looks like atom-runner on Windows uses cp1252 (Windows 1252) encoding by default instead of utf-8.

As a work-around you can specify the encoding as utf-8 in your code for the system out and error streams:

```
import sys
import io

sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding = 'utf-8')
sys.stderr = io.TextIOWrapper(sys.stderr.detach(), encoding = 'utf-8')

print ('(汉语/漢語')
```

**Comment by lsegal** [comment]
Marking as closed since this is likely an Atom-runner issue. This plugin does not, and should not, need to modify encodings.

**Comment by garmo** [comment]
As mentioned @dbolton that worked for me. So, thank you very much
