### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by eFiggy** [lsegal/atom-runner#59]
Requiring `ScrollView` from `atom` is no longer supported.
Please require `ScrollView` from `atom-space-pen-view` instead:
  `{ScrollView} = require 'atom-space-pen-views'`
Note that the API has changed slightly! Please read the docs at https://github.com/atom/atom-space-pen-views
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
```
Object.Object.defineProperty.get (C:\Users\Edwin\AppData\Local\atom\app-0.198.0\resources\app.asar\exports\atom.js:84:11)
Object.<anonymous> (C:\Users\Edwin\.atom\packages\atom-runner\lib\atom-runner-view.coffee:1:1)
Object.<anonymous> (C:\Users\Edwin\.atom\packages\atom-runner\lib\atom-runner-view.coffee:94:4)
Module._compile (module.js:452:26)
```

**Comment by avand** [comment]
+1

**Comment by bscharm** [comment]
:+1:
