### ISSUE TITLE
config

### ISSUE THREAD

**Issue by di48l069** [lsegal/atom-runner#70]
hi there i pasted below in config file

```
'runner':
  'scopes':
    'coffee': 'coffee'
    'js': 'node'
    'ruby': 'ruby'
    'python': 'python'
    'go': 'go run'
    'shell': 'bash'
    'powershell': 'c:\\windows\\sysnative\\windowspowershell\\v1.0\\powershell.exe -noninteractive -noprofile -c -'
  'extensions':
    'spec.coffee': 'mocha'
    'ps1': 'c:\\windows\\sysnative\\windowspowershell\\v1.0\\powershell.exe –file'
```

And it now looks like this

```
"*":
  "exception-reporting":
    userId: "6b5abfae-0e4c-2164-b4e7-ee718c52f8d5"
  welcome:
    showOnStartup: false
  "tree-view":
    showOnRightSide: true
  editor:
    invisibles: {}
  core: {}
  'runner':
  'scopes':
    'coffee': 'coffee'
    'js': 'node'
    'ruby': 'ruby'
    'python': 'python'
    'go': 'go run'
    'shell': 'bash'
    'powershell': 'c:\\windows\\sysnative\\windowspowershell\\v1.0\\powershell.exe -noninteractive -noprofile -c -'
  'extensions':
    'spec.coffee': 'mocha'
    'ps1': 'c:\\windows\\sysnative\\windowspowershell\\v1.0\\powershell.exe –file'
```
But does not work it throws a error 

```
Failed to load config.cson
[stdin]:11:12: error: unexpected newline
  'runner':
```

What am i doing wrong?

**Comment by lsegal** [comment]
You cannot have an empty member in cson. Simply omit that member.

**Comment by di48l069** [comment]
sorry i don't really understand i'm rather new to atom.

**Comment by kferrari** [comment]
As far as I can tell, the indentation is wrong. Also in the example, it looks like this:

<pre><code>
'runner':
  'scopes':
    'coffee': 'coffee'
    'js': 'node'
    'ruby': 'ruby'
    'python': 'python'
    'go': 'go run'
    'shell': 'bash'
    'powershell': 'c:\\windows\\sysnative\\windowspowershell\\v1.0\\powershell.exe -noninteractive -noprofile -c -'
  'extensions':
    'spec.coffee': 'mocha'
    'ps1': 'c:\\windows\\sysnative\\windowspowershell\\v1.0\\powershell.exe –file'</code>

So <code>'runner':</code> needs to be one level higher.

**Comment by di48l069** [comment]
@kferrari perfect thanks it works :+1:

**Comment by lsegal** [comment]
Glad you got it working!
