### ISSUE TITLE
How to give input from Console

### ISSUE THREAD

**Issue by shoaib10a** [lsegal/atom-runner#72]
I can't give input from console. I am using python and raw_input() doesn't work.
it states-
EOFError: EOF when reading a line

**Comment by lsegal** [comment]
This is a duplicate of #42. Input is not supported in atom-runner.

**Comment by shoaib10a** [comment]
Sorry @lsegal . Didn't see that. Great package though.

**Comment by RachitSinghal** [comment]
Is there any other way to take input from keyboard using atom runner
