### ISSUE TITLE
[OSX] cmd + R doesn't run anything

### ISSUE THREAD

**Issue by hawsome** [lsegal/atom-runner#73]
After I get this prompt and press `enter` nothing happens:
![screen shot 2015-07-07 at 7 39 04 am](https://cloud.githubusercontent.com/assets/567126/8548719/4b90c366-247b-11e5-842e-cce0e12a4e58.png)

**Comment by mbrochh** [comment]
You need to use CTRL+R

If you are using `vim-mode`, you need to activate input mode first.

**Comment by lsegal** [comment]
Seems to be related to overloaded key bindings. Closing.
