### ISSUE TITLE
spawn go ENOENT 

### ISSUE THREAD

**Issue by thewhitetulip** [lsegal/atom-runner#74]
When I hit run it gives me this error.

Atom Runner: one.go

Error: spawn go ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
    at child_process.js:1127:20
    at process._tickCallback (node.js:357:13)

**Comment by Rod-0** [comment]
Same thing for me !

Error: spawn python ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
    at child_process.js:1127:20
    at process._tickCallback (node.js:357:13)

**Comment by thewhitetulip** [comment]
Hey, put #!/usr/bin/python like thing for go, that was the solution

**Comment by dreftymac** [comment]
**//  thing for go //**

(aka interpreter directive, aka shebang line)

https://en.wikipedia.org/wiki/Shebang_(Unix)

**Comment by thewhitetulip** [comment]
An alternative is don't use Atom and use VI with the vim-go plugin :D

**Comment by lsegal** [comment]
The real solution here is to ensure that `go` is in your environment / path when executing Atom.

**Comment by thewhitetulip** [comment]
@isegal actually go is in my PATH variable an env yet atom-runner doesn't run anything

**Comment by lsegal** [comment]
@thewhitetulip are you sure Atom picked up the PATH? See #23 for background info and the updated README for a FAQ. If you're on OSX and running Atom through the launcher or Dock, note that it may not be picking up your path info.

You can verify what the path is by running the following script in atom-runner:

```
#!/bin/sh
echo $PATH
```

**Comment by isegal** [comment]
I think @thewhitetulip got the wrong Segal, but it's a nice discovery. :)

**Comment by thewhitetulip** [comment]
@isegal  Haha true that :)
