### ISSUE TITLE
It doesn't honor active virtualenv in Python

### ISSUE THREAD

**Issue by mbrochh** [lsegal/atom-runner#79]
Even when I activate a Python virtualenv before starting Atom, this plugin cannot find the packages installed in that virtualenv. So I guess this package always looks at the global Python installation?

Would it be possible to extend the package somehow so that it is aware when a virtualenv is activated?

**Comment by lsegal** [comment]
My guess is that your environment is not correctly setup. See #23 for an example. You can echo your PATH env from a Python script to see which binary it is using. The best way to solve this is to either configure a direct path to your virtualenv python or launch Atom via the terminal to pull in your correct environment variables.

**Comment by mbrochh** [comment]
I am launching atom from the terminal (after activating the virtualenv).

**Comment by wandonye** [comment]
looks like this is happening again
