### ISSUE TITLE
Send output to local temporary file instead of standard output pane

### ISSUE THREAD

**Issue by dreftymac** [lsegal/atom-runner#82]
## Details
If there were a configurable option to send the output to a local temp file instead of,  or in addition to, the standard command pane, this would enable things like:

* searching on the output (See also #75)
* copy/paste output into another place
* support for anything atom can do with a text file

## See also
* request for support for configurable output pane (#78)

**Comment by lsegal** [comment]
I would recommend opening an issue with Atom to add search/copy support to all panes, since that seems to be the real blocker. There's no reason why Atom should not be able to treat any pane as text, which would remove the need for this option.

**Comment by dreftymac** [comment]
@lsegal Excellent, thanks for the lead.
