### ISSUE TITLE
CTRL+C keybinding (clipboard copy) does not work in output view

### ISSUE THREAD

**Issue by clupascu** [lsegal/atom-runner#83]
In output view, pressing <kbd>CTRL</kbd>+<kbd>C</kbd> does not copy the selected text to clipboard, although [the keymap file](https://github.com/lsegal/atom-runner/blob/513fac745f3ad5a5e840b823af223442b8427380/keymaps/atom-runner.cson) seems to address this.

It works fine using [the context menu](https://github.com/lsegal/atom-runner/pull/76), but I'm so used to the keyboard shortcut that I find this distracting.

I'm using Windows 8.1

**Comment by lsegal** [comment]
Similar to #82, I'd recommend opening this as an issue against Atom instead. A plugin should not have to implement copy-paste functionality, that should be handled generically across the editor for all windows where text can be highlighted.

**Comment by clupascu** [comment]
Right, this is actually a subset of #82, so I will close it.
