### ISSUE TITLE
Output pane should follow theme colors

### ISSUE THREAD

**Issue by RomFouq** [lsegal/atom-runner#84]
The output pane should follow the theme colors, especially for background.
So https://github.com/lsegal/atom-runner/blob/master/styles/atom-runner.less#L8 should be:
```css
background: @pane-item-background-color;
```
But the output isn't anymore highlighted, so I propose to change https://github.com/lsegal/atom-runner/blob/master/styles/atom-runner.less#L15 to:
```css
background-color: @pane-item-border-color;
```
that makes it darker than the pane background.

I can make a PR it you want one, but I think it's not necessary for so little changes.

**Comment by MadcapJake** [comment]
This is a great idea! I love atom runner but I really would like to have it mesh with my dark theme.

**Comment by Kosyne** [comment]
Same here. Thanks for posting the solution though, RomFouq.

**Comment by lsegal** [comment]
I would pull this in if someone put together a quick PR!

**Comment by RomFouq** [comment]
Done in #91.

**Comment by lsegal** [comment]
Merged and published in 2.4.6.

**Comment by ansmonjol** [comment]
Hi,
I still have trouble with the output text color.
Here is a screenshot with my theme settings and and output exemple (if you watch attentively, you can see the output)

<img width="1920" alt="screen shot 2016-08-27 at 19 23 26" src="https://cloud.githubusercontent.com/assets/5517077/18029316/c06e4582-6c8c-11e6-98b8-5606bb8f20fe.png">

Is it possible to set manually the output color/background ?

**Comment by ShreyanshLodha** [comment]
Changing it from the original package is not possible. But, we can do it from the outside.
What I mean is that you can style it from outside.
Just open your Stylesheet of ATOM
and place the following code

```
   pre{
       color :    //set the color you want to set
}
```

```pre``` is the selector for the output window in the atom runner. 
so by changing its ```color``` property you can change the color of the text.

**Comment by ansmonjol** [comment]
It works perfectly, thank you @ShreyanshLodha

**Comment by ShreyanshLodha** [comment]
Welcome @ansmonjol.
Hope it helps others as well.
