### ISSUE TITLE
Long startup time

### ISSUE THREAD

**Issue by timthejiang** [lsegal/atom-runner#86]
atom-runner adds `115ms` to my startup time, while the [atom-script](https://github.com/rgbkrk/atom-script) only adds `10ms`.  It seems that all-around, atom-runner is heavier than atom-script.  How could it be improved?

**Comment by lsegal** [comment]
It's kind of a misleading metric, but it is possible to lower that number, patch incoming. Basically, atom-runner is being loaded fully on start and not using `activationEvents` to delay loading of the plugin until first execution. If you *actively* use atom-runner, you will still see that ~115ms delay on first execution, it's not going anywhere, just moved to be less visible. I can understand why someone would want a quick startup time, though, so I can make this change.
