### ISSUE TITLE
Can't handle pythons input-function

### ISSUE THREAD

**Issue by rolfpancake** [lsegal/atom-runner#93]
**Issue:**
When using input-function it throws EOFError.

**Codesnippet:**
```python
the_input = str(input("Your input: "))
print(the_input)
```

**Output:**
```
Your input: Traceback (most recent call last):
  File "...\inputting.py", line 1, in <module>
    the_input = str(input("Your input: "))
EOFError: EOF when reading a line
```

**PS:** I really like your package. It is nice and handy, thanks for this! :+1:

**Comment by lsegal** [comment]
This is a duplicate of #42, atom-runner does not (yet?) support reading from standard input.

**Comment by rolfpancake** [comment]
Damn. A duplicate of a duplicate. I'm sorry.

**Comment by lsegal** [comment]
No problem, this should probably go into the FAQ in the README.

**Comment by Neerajadhiari** [comment]
lsegal how can use input function in atom
