### ISSUE TITLE
Support for UTF-8

### ISSUE THREAD

**Issue by rolfpancake** [lsegal/atom-runner#94]
> A docked runner window with ANSI support [...]

Is it possible to support UTF-8 characters?

**Comment by lsegal** [comment]
UTF-8 should be supported, as long as the glyphs exist in the font used in your theme.

**Comment by rolfpancake** [comment]
So then it is not atom-runner related?
I tried to use chars like ä, ö, ü or ¾ and got these �

__My config__
UI Theme: One Light
Syntax Theme: Serious Business
Font: (Should be) Consolas

**Comment by lsegal** [comment]
As mentioned, it's dependent entirely on the capabilities of the font. atom-runner is rendered as a div inside the larger Atom workspace DOM, so it shares the exact same character encoding (and in fact, there is no way to change this even if I wanted to). You can see how a bunch of characters render equivalently in the following screenshot:

![image](https://cloud.githubusercontent.com/assets/686/10676505/843784ae-78bb-11e5-8321-9917b049adce.png)

Note that even the editor is unable to render some of the glyphs. Choose a font that supports more of the Unicode space and it should render the glyphs properly.

**Comment by rolfpancake** [comment]
Well thanks for explanation.
It just confuses me that my editor handles the character encoding correctly and my runner window does not:
![font_difference_runner](https://cloud.githubusercontent.com/assets/9326192/10676937/bef648c0-7909-11e5-9aed-b629455f22ae.png)
Could this be an atom-config related thing?

**Comment by lsegal** [comment]
It could be. Could also be a Python encoding thing. I would check the output of that in your terminal first. If I recall, the � glyph in Python implies some kind of encoding error, but I don't know enough about Python to be sure. I do know Python encodings between v2 and v3 can be confusing, though.

**Comment by rolfpancake** [comment]
In Terminal the encoding works perfectly. I'm using Python 3+ which has (if I am not wrong) full utf-8 support and my terminal font (Consolas) too.
I will investigate this further when I got time for this. Due to the fact that this is not an atom-runner related thing this issue can be closed imho.

**Comment by dbolton** [comment]
@rolfpancake I came across the same problem. It looks like atom-runner on Windows uses cp1252 (Windows 1252) encoding by default instead of utf-8.

As a work-around you can specify the encoding as utf-8 in your code for the system out and error streams: 

```
import sys
import io

sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding = 'utf-8')
sys.stderr = io.TextIOWrapper(sys.stderr.detach(), encoding = 'utf-8')

print ("ß, ä, ö, ü, ¾")
```

**Comment by rolfpancake** [comment]
Thanks for this workaround.
Works perfectly :+1:
