### ISSUE TITLE
Atom-Runner

### ISSUE THREAD

**Issue by KaptainKartoon** [lsegal/atom-runner#95]
I'm new to programming and just downloaded atom and have no idea how to get the atom-runner package to work

**Comment by lsegal** [comment]
@KaptainKartoon have you taken a look at the [README](https://github.com/lsegal/atom-runner/blob/master/README.md)?

**Comment by KaptainKartoon** [comment]
Yes but I'm still unsure how to configure it. Am I supposed to copy and paste that somewhere?

**Comment by lsegal** [comment]
@KaptainKartoon there's nothing to configure. Once Atom has installed the plugin you can run code by reading and following the instructions in the Using section. Configuration is optional and only needed if you want to add other languages or change paths to binaries.

**Comment by KaptainKartoon** [comment]
In order to ensure that your PATH is correctly configured in OS X, it is recommended to load Atom only through an active terminal (i.e., the atom command).

What does this mean?

**Comment by lsegal** [comment]
@KaptainKartoon it means using the `atom` command in your terminal to launch Atom. See the [Atom on Mac](https://atom.io/docs/v1.1.0/getting-started-installing-atom) section of the getting started guide.

**Comment by KaptainKartoon** [comment]
Thanks! I figured it out

**Comment by lsegal** [comment]
Great! We can close this now.
